coverage:
  status:
    project:
      integration:
        target: 60%
        flags:
          - totalTest
flags:
  totalTest:
    paths:
      - ./potatocountry/potatocountry/src/main/java/com/potatocountry
