coverage:
  status:
    project:
      default: false
      totalTest:
        target: 60%
        threshold: 10%
        flags:
          - totalTest
flags:
  totalTest:
    paths:
      - ./potatocountry
