coverage:
  status:
    project:
      unit:
        target: 1%
        flags:
          - unitTest
      integration:
        target: 60%
        flags:
          - integrationTest
flags:
  unitTest:
    paths:
      - potatocountry/src/main/java/com/potatocountry
  integrationTest:
    paths:
      - potatocountry/src/main/java/com/potatocountry
